name: CI

on:
  push:
    branches: [main]

jobs:
  Repositoryani_yuklash:
    runs-on: ubuntu-latest
    steps:
      - name: Repo yuklanayapti
        uses: actions/checkout@v4

  Install:
    runs-on: ubuntu-latest
    steps:
      - name: node_modules papkasini yuklash
        run: npm i
